### ISSUE TITLE
"terminate QtE" leaves atd process running

### ISSUE THREAD

**Issue by ydirson** [radekp/qtmoko#74]
Since this process is run from /opt/qtmoko/bin, when running from NFS-mounted /opt/qtmoko we can't umount it after terminating because of this process.

**Comment by radekp** [comment]
Hi, do you mean terminating from the POWER key menu? /etc/inid.d/qtmoko stop should be ok since it has:

killall -q qpe atd quicklauncher mediaserver mediaplayer sipagent telepathyagent

Maybe we should move this to qpe.sh script? Can you try it? The script is in devices/neo/scr/devtools/startup/qpe.sh IIRC

**Comment by ydirson** [comment]
Right. And since it is even launched by qpe.sh, it makes a lot of sense to move the killing there. Patch under way.

**Comment by ydirson** [comment]
Merged with #75
